### ISSUE TITLE
Requires specific commit of marlon-ogone

### ISSUE THREAD

**Issue by Intrepidity** [snowcap/SnowcapOgoneBundle#4]
Since the marlon-ogone bundle has renamed some classes (PaymentRequest --> EcommercePaymentRequest for example) this bundle relies on a specific commit of that library. I think this should be fixed. We're dealing with online payment here, and specifically relying on old code isn't a good idea.
Aside of changing references to class names, does something need to happen to make this bundle compatible with newer versions? I've changed only 3 or 4 lines to make it compatible with the newest version of the library, but maybe I'm missing something here.. I'll recheck my code and run some tests and send a PR, but if anyone has other suggestions, bring them on :)

**Comment by kpicaza** [comment]
I have the same problem with latest verison of both Marlon-be/Ogone and SnowCap/OgoneBundle.

I fix by changing used namespace on OgoneBundle SimpleFormGenerator class:

remove:
use Ogone\PaymentRequest;

add:
use Ogone\Ecommerce\EcommercePaymentRequest as PaymentRequest;

And then the bundle works again :-D

**Comment by Moinax** [comment]
Yeah, that's my bad, I revert a previous commit due to a legacy project.

I just corrected that by creating a "legacy" tag.

Now you will find a v1.0.1 tag/release with the right code.

Regards,
